"""Generated adapters: one canonical source, thin per-agent wrappers, identical instruction body."""

from __future__ import annotations

import json
from pathlib import Path
import re
import shutil
import tomllib

import pytest

from noetic.adapters import REGISTRY, sync
from noetic.adapters.base import BLOCK_RE, HEADER_PREFIX, Canonical, apply_block
from noetic.adapters.gemini import toml_multiline
from noetic.adapters.sync import ENGINE_DIR, SEED_DIR, load_canonical

ALL = ["claude", "codex", "gemini", "antigravity"]
HEADER_RE = re.compile(r"GENERATED by noetic sync from (.+) \(hash ([0-9a-f]{12})\) - do not edit")


def strip_frontmatter(text: str) -> str:
  m = re.match(r"---\n.*?\n---\n", text, re.S)
  return text[m.end():] if m else text


def read(p: Path) -> str:
  return p.read_bytes().decode("utf-8").replace("\r\n", "\n")


@pytest.fixture
def source(tmp_path: Path) -> Path:
  """A throwaway canonical tree (so tests can add/remove commands without touching the repo)."""
  src = tmp_path / "src"
  shutil.copytree(ENGINE_DIR.parent / "workflows" / "taste_engine" / "commands", src / "commands")
  shutil.copytree(ENGINE_DIR / "agents", src / "agents", ignore=shutil.ignore_patterns("_*", "*.py", "__pycache__"))
  shutil.copyfile(SEED_DIR / "AGENTS.block.md", src / "AGENTS.block.md")
  return src


@pytest.fixture
def v(tmp_path: Path) -> Path:
  d = tmp_path / "vault"
  d.mkdir()
  return d


def test_generated_files_have_header_and_expected_targets(v, source):
  report = sync(v, ALL, source=source)
  assert report.agents == ALL
  for f in [".claude/commands/apply.md", ".gemini/commands/apply.toml", ".agent/skills/overmind-apply/SKILL.md"]:
    head = read(v / f)
    assert HEADER_RE.search(head[:600]), f
    assert "commands/apply.md" in head[:600]
  for f in ["CLAUDE.md", "AGENTS.md", "GEMINI.md"]:
    text = read(v / f)
    assert "<!-- overmind:start -->" in text and "<!-- overmind:end -->" in text
    assert HEADER_RE.search(text)
  assert (v / ".claude/agents").is_dir() and (v / ".agent/skills/overmind").is_dir()


def test_body_is_byte_identical_across_all_adapters(v, source):
  sync(v, ALL, source=source)
  for src in sorted((source / "commands").glob("*.md")):
    body = strip_frontmatter(read(src))
    name = src.stem
    claude = read(v / ".claude/commands" / f"{name}.md")
    claude_body = claude[claude.index("-->\n\n") + 5:]
    gemini = tomllib.loads(read(v / ".gemini/commands" / f"{name}.toml"))["prompt"]
    skill = read(v / ".agent/skills" / f"overmind-{name}" / "SKILL.md")
    skill_body = skill[skill.index("-->\n\n") + 5:]
    assert claude_body == gemini == skill_body == body, name
  for src in sorted((source / "agents").glob("*.md")):
    body = strip_frontmatter(read(src))
    slug = src.stem.replace("_", "-")
    c = read(v / ".claude/agents" / f"{slug}.md")
    a = read(v / ".agent/skills" / f"overmind-agent-{slug}" / "SKILL.md")
    assert c[c.index("-->\n\n") + 5:] == a[a.index("-->\n\n") + 5:] == body


def test_instruction_block_identical_in_claude_agents_gemini(v, source):
  sync(v, ALL, source=source)
  bodies = []
  for f in ["CLAUDE.md", "AGENTS.md", "GEMINI.md"]:
    m = BLOCK_RE.search(read(v / f))
    inner = m.group(0).split("-->\n\n", 1)[1].rsplit("<!-- overmind:end -->", 1)[0]
    bodies.append(inner)
  assert bodies[0] == bodies[1] == bodies[2]
  canon = load_canonical(v, {}, source)
  assert bodies[0] == canon.block_body()
  skill = read(v / ".agent/skills/overmind/SKILL.md")
  assert skill.endswith(canon.block_body())  # the antigravity skill carries the same body too


def test_sync_is_idempotent_and_dry_run_writes_nothing(v, source):
  dry = sync(v, ALL, dry_run=True, source=source)
  assert dry.dry_run and dry.changed and not any(v.iterdir())
  first = sync(v, ALL, source=source)
  snap = {p: p.read_bytes() for p in v.rglob("*") if p.is_file()}
  second = sync(v, ALL, source=source)
  assert first.changed and not second.changed
  assert snap == {p: p.read_bytes() for p in v.rglob("*") if p.is_file()}


def test_user_content_outside_markers_is_preserved(v, source):
  (v / "CLAUDE.md").write_text("# Mine\n\nkeep me top\n", encoding="utf-8")
  sync(v, ["claude"], source=source)
  text = read(v / "CLAUDE.md")
  (v / "CLAUDE.md").write_bytes((text + "\nkeep me bottom\n").encode())
  sync(v, ["claude"], source=source)
  text = read(v / "CLAUDE.md")
  assert text.startswith("# Mine\n\nkeep me top\n") and text.rstrip().endswith("keep me bottom")
  assert text.count("<!-- overmind:start -->") == 1


def test_legacy_overmind_block_is_migrated():
  legacy = "# T\n\nmine\n\n<!-- taste-engine:start -->\nold\n<!-- taste-engine:end -->\n\ntail\n"
  out = apply_block(legacy, "<!-- overmind:start -->\nnew\n<!-- overmind:end -->\n", "# x")
  assert "old" not in out and "new" in out and "mine" in out and "tail" in out


def test_no_personal_data_in_generated_files(v, source):
  (v / "taste-engine.config.json").write_text(
    json.dumps({"owner": "Zaphod Beeblebrox", "agent": "Claude Code"}), encoding="utf-8")
  sync(v, ALL, source=source)
  blob = "\n".join(read(p) for p in v.rglob("*") if p.is_file() and p.name != "taste-engine.config.json")
  assert "Zaphod" not in blob and "Beeblebrox" not in blob
  assert str(v) not in blob and str(Path.home()) not in blob
  assert not re.search(r"[\w.+-]+@[\w-]+\.[\w.]+", blob)
  assert not re.search(r"[A-Za-z]:\\\\?Users", blob)


def test_new_command_appears_in_every_adapter(v, source):
  sync(v, ALL, source=source)
  (source / "commands" / "zzz-newcmd.md").write_text(
    "---\ndescription: A brand new command\nargument-hint: <x>\n---\n\n# /zzz-newcmd\nDo the thing: $ARGUMENTS\n",
    encoding="utf-8")
  rep = sync(v, ALL, source=source)
  assert rep.changed
  assert (v / ".claude/commands/zzz-newcmd.md").is_file()
  t = tomllib.loads(read(v / ".gemini/commands/zzz-newcmd.toml"))
  assert t["description"] == "A brand new command" and "Do the thing" in t["prompt"]
  assert (v / ".agent/skills/overmind-zzz-newcmd/SKILL.md").is_file()
  for f in ["CLAUDE.md", "AGENTS.md", "GEMINI.md"]:
    assert "`/zzz-newcmd <x>`: A brand new command" in read(v / f)


def test_removed_command_is_pruned_but_user_files_are_not(v, source):
  (source / "commands" / "temp.md").write_text("---\ndescription: t\n---\nbody\n", encoding="utf-8")
  sync(v, ALL, source=source)
  (v / ".claude/commands/mine.md").write_text("my own command\n", encoding="utf-8")
  (source / "commands" / "temp.md").unlink()
  rep = sync(v, ALL, source=source)
  assert not (v / ".claude/commands/temp.md").exists()
  assert not (v / ".agent/skills/overmind-temp").exists()
  assert not (v / ".gemini/commands/temp.toml").exists()
  assert (v / ".claude/commands/mine.md").read_text(encoding="utf-8") == "my own command\n"
  assert any(f.action == "removed" for f in rep.files)


def test_hand_written_file_with_same_name_is_not_overwritten(v, source):
  (v / ".claude/commands").mkdir(parents=True)
  (v / ".claude/commands/apply.md").write_text("hand written\n", encoding="utf-8")
  rep = sync(v, ["claude"], source=source)
  assert (v / ".claude/commands/apply.md").read_text(encoding="utf-8") == "hand written\n"
  assert any(f.action == "skipped" and f.path.endswith("apply.md") for f in rep.files)


def test_legacy_raw_copy_of_a_command_is_upgraded(v, source):
  (v / ".claude/commands").mkdir(parents=True)
  shutil.copyfile(source / "commands" / "apply.md", v / ".claude/commands/apply.md")
  sync(v, ["claude"], source=source)
  assert HEADER_PREFIX in read(v / ".claude/commands/apply.md")


def test_gemini_toml_roundtrips_awkward_bodies():
  for body in ["plain\n", "has ''' triple\nand \\ backslash\n", "ends with quote'", 'ends "dq"', 'x """ y\n', ""]:
    parsed = tomllib.loads(f"prompt = {toml_multiline(body)}\n")["prompt"]
    assert parsed == body


def test_agent_selection_config_alias_and_errors(v, source):
  (v / "taste-engine.config.json").write_text(json.dumps({"adapters": ["gemini"]}), encoding="utf-8")
  assert sync(v, None, source=source).agents == ["gemini"]
  assert (v / "GEMINI.md").exists() and not (v / "CLAUDE.md").exists() and not (v / "AGENTS.md").exists()
  assert sync(v, ["agy"], source=source).agents == ["antigravity"]
  with pytest.raises(ValueError):
    sync(v, ["nope"], source=source)


def test_codex_and_universal_share_agents_md_without_conflict(v, source):
  rep = sync(v, ["codex", "universal"], source=source)
  assert sum(1 for f in rep.files if f.path == "AGENTS.md") == 1
  assert any("user-level" in n for n in rep.notes)


def test_repo_default_source_includes_pack_commands_and_agents(v):
  canon = load_canonical(v, {})
  names = {c.name for c in canon.commands}
  assert {"apply", "curate", "ingest", "research", "draft", "ship", "journey"} <= names
  assert {a.name for a in canon.agents} == {p.stem for p in (ENGINE_DIR / "agents").glob("*.md") if not p.name.startswith("_")}


def test_every_registered_adapter_renders_without_io(source, v):
  canon = load_canonical(v, {}, source)
  for name, cls in REGISTRY.items():
    files = cls().render(canon)
    assert files and all(f.content for f in files), name
    assert cls().targets(canon) == [f.path for f in files]
