"""Adapter interface and the canonical model.

The canonical sources (workflows/*/commands, overmind/agents, the constitution block) are
provider-neutral markdown. Adapters only *wrap* them for one agent CLI: the instruction
body is carried through byte-for-byte, only the surrounding format differs. Nothing
generated here is ever a source of truth.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
import re

START = "<!-- overmind:start -->"
END = "<!-- overmind:end -->"
LEGACY_BLOCK_RE = re.compile(r"<!-- taste-engine:start -->.*?<!-- taste-engine:end -->\r?\n?", re.S)
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\r?\n?", re.S)
HEADER_PREFIX = "GENERATED by overmind sync from "


def short_hash(parts: list[tuple[str, str]]) -> str:
  h = hashlib.sha256()
  for name, text in parts:
    h.update(name.encode("utf-8") + b"\0" + text.encode("utf-8") + b"\0")
  return h.hexdigest()[:12]


def header_text(sources: list[tuple[str, str]]) -> str:
  names = ", ".join(n for n, _ in sources)
  return f"{HEADER_PREFIX}{names} (hash {short_hash(sources)}) - do not edit"


def render_template(text: str, values: dict[str, str]) -> str:
  """Fill {{placeholders}}; a line whose placeholder resolves to '' is dropped."""
  out = []
  for line in text.split("\n"):
    keys = re.findall(r"\{\{(\w+)\}\}", line)
    if any(k in values and values[k] == "" for k in keys):
      continue
    out.append(re.sub(r"\{\{(\w+)\}\}", lambda m: values.get(m.group(1), m.group(0)), line))
  return "\n".join(out)


def parse_markdown(text: str) -> tuple[dict[str, str], str, str]:
  """Return (frontmatter dict, raw frontmatter lines, body). Body is untouched text."""
  text = text.replace("\r\n", "\n")
  m = re.match(r"---\n(.*?)\n---\n", text, re.S)
  if not m:
    return {}, "", text
  fm = {}
  for line in m.group(1).split("\n"):
    k, sep, v = line.partition(":")
    if sep and not line.startswith((" ", "\t")):
      fm[k.strip()] = v.strip()
  return fm, m.group(1), text[m.end():]


@dataclass(frozen=True)
class Item:
  """One canonical command or agent."""
  kind: str  # "command" | "agent"
  name: str  # file stem
  description: str
  body: str
  source: str  # label used in headers, e.g. commands/apply.md
  raw_frontmatter: str = ""
  argument_hint: str = ""
  text: str = field(default="", repr=False)  # full source text, hashed into headers

  @property
  def slug(self) -> str:
    return re.sub(r"[^a-z0-9]+", "-", self.name.lower()).strip("-")


def _description(fm: dict, body: str, name: str) -> str:
  if fm.get("description"):
    return fm["description"]
  for line in body.split("\n"):
    if line.startswith("#"):
      return line.lstrip("#").strip()
  return name


def _load_dir(kind: str, label: str, directory: Path) -> list[Item]:
  items = []
  for f in sorted(directory.glob("*.md")) if directory.is_dir() else []:
    if f.name.startswith("_"):  # shared fragments (_contract.md, _preamble.md) are not canonical items
      continue
    text = f.read_bytes().decode("utf-8").replace("\r\n", "\n")
    fm, raw, body = parse_markdown(text)
    items.append(Item(kind, f.stem, _description(fm, body, f.stem), body, f"{label}/{f.name}", raw,
                      fm.get("argument-hint", ""), text))
  return items


@dataclass
class Canonical:
  commands: list[Item]
  agents: list[Item]
  constitution: str  # rendered AGENTS.block.md body
  constitution_source: str
  engine_dir: str  # vault-relative engine folder (for pointers)

  @classmethod
  def load(cls, command_dirs: list[Path], agent_dirs: list[Path], constitution_path: Path,
           values: dict[str, str]) -> "Canonical":
    commands: dict[str, Item] = {}
    for d in command_dirs:
      for it in _load_dir("command", "commands", d):
        commands[it.name] = it
    agents: dict[str, Item] = {}
    for d in agent_dirs:
      for it in _load_dir("agent", "agents", d):
        agents[it.name] = it
    raw = constitution_path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    return cls(sorted(commands.values(), key=lambda i: i.name), sorted(agents.values(), key=lambda i: i.name),
               render_template(raw, values).strip("\n") + "\n", constitution_path.name,
               values.get("engine", "taste-engine"))

  def sources(self) -> list[tuple[str, str]]:
    return ([(self.constitution_source, self.constitution)]
            + [(i.source, i.text) for i in self.commands] + [(i.source, i.text) for i in self.agents])

  def block_body(self) -> str:
    """The instruction body shared verbatim by CLAUDE.md, AGENTS.md and GEMINI.md blocks."""
    lines = [self.constitution.rstrip("\n"), "", "## Commands", ""]
    lines.append(f"Full text of each command: `{self.engine_dir}/canonical/commands/<name>.md`. "
                 "When asked to run `/name`, read that file and follow it exactly.")
    lines.append("")
    for c in self.commands:
      hint = f" {c.argument_hint}" if c.argument_hint else ""
      lines.append(f"- `/{c.name}{hint}`: {c.description}")
    if self.agents:
      lines += ["", "## Agent contracts", "",
                f"Full text: `{self.engine_dir}/canonical/agents/<name>.md`.", ""]
      lines += [f"- `{a.name}`: {a.description}" for a in self.agents]
    return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class OutFile:
  path: str  # vault-relative, posix
  content: str  # full file (mode "file") or the block (mode "block")
  mode: str = "file"  # "file" | "block"
  preamble: str = ""  # used when a block file does not exist yet
  adapter: str = ""


def block(canon: Canonical) -> str:
  head = header_text(canon.sources())
  return f"{START}\n<!-- {head} -->\n\n{canon.block_body()}{END}\n"


def apply_block(existing: str | None, new_block: str, preamble: str) -> str:
  if existing is None:
    return f"{preamble}\n\n{new_block}"
  if BLOCK_RE.search(existing):
    return BLOCK_RE.sub(lambda _: new_block, existing, count=1)
  if LEGACY_BLOCK_RE.search(existing):
    return LEGACY_BLOCK_RE.sub(lambda _: new_block, existing, count=1)
  return existing.rstrip() + "\n\n" + new_block


def md_with_header(frontmatter: str, item_sources: list[tuple[str, str]], body: str) -> str:
  fm = f"---\n{frontmatter}\n---\n" if frontmatter else ""
  return f"{fm}<!-- {header_text(item_sources)} -->\n\n{body}"


def yaml_str(s: str) -> str:
  return json.dumps(s, ensure_ascii=False)


class Adapter(ABC):
  name: str = ""
  #: dirs (vault-relative) whose generated files are pruned when the canonical item is gone
  managed_dirs: tuple[str, ...] = ()
  notes: tuple[str, ...] = ()

  @abstractmethod
  def detect(self, vault: Path) -> bool:
    """Heuristic: does the vault already show signs of this agent?"""

  @abstractmethod
  def render(self, canon: Canonical) -> list[OutFile]:
    """Wrap the canonical content for this agent. Pure: no filesystem access."""

  def targets(self, canon: Canonical) -> list[str]:
    return [f.path for f in self.render(canon)]
