"""Knowledge layer: write notes into the vault.

Renders validated agent JSON into vault markdown.

Python, not the agent, writes every file. Each note gets the pipeline
frontmatter (status: pending_review + run id), so the human gate is always
visible in Obsidian.
"""

from __future__ import annotations

from pathlib import Path
import re

from taste_engine.knowledge.config import Config, slugify, today

STATUS_FLOW = ("pending_review", "approved", "published", "rejected")


def frontmatter(cfg: Config, agent: str, run_id: str, kind: str, extra: dict | None = None) -> str:
  lines = [
    "---",
    "author: ai-agent",
    f"agent: {cfg.agent} · pipeline/{agent}",
    f"created: {today()}",
    f"type: {kind}",
    "status: pending_review",
    f"run: {run_id}",
  ]
  for key, value in (extra or {}).items():
    lines.append(f"{key}: {value}")
  lines += [
    "---",
    f"> [!NOTE] Generated by the Taste Engine pipeline ({agent}) · run `{run_id}` · "
    f"**pending {cfg.owner}'s review**. Approve: `pipeline.py approve \"<this file>\"`.",
    "",
  ]
  return "\n".join(lines) + "\n"


def unique_path(path: Path) -> Path:
  """Never overwrite: foo.md → foo-2.md → foo-3.md."""
  if not path.exists():
    return path
  n = 2
  while (candidate := path.with_name(f"{path.stem}-{n}{path.suffix}")).exists():
    n += 1
  return candidate


def write(path: Path, text: str) -> Path:
  path = unique_path(path)
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(text, encoding="utf-8")
  return path


def bullets(items, empty="-") -> str:
  return "\n".join(f"- {i}" for i in items) if items else empty


def wikilink(cfg: Config, path_or_name: str) -> str:
  """Turn a vault path into [[wikilink]]; leave URLs alone."""
  if path_or_name.startswith("http"):
    return path_or_name
  rel = path_or_name.replace("\\", "/")
  if rel.endswith(".md"):
    rel = rel[:-3]
  return f"[[{rel}]]"


# ── per-type renderers ──────────────────────────────────────────────────────

def framework(cfg: Config, d: dict, agent: str, run_id: str) -> Path:
  src = d["source"]
  source_line = f"{src['title']}" + (f" — {src['author']}" if src["author"] else "") + (f" ({src['url']})" if src["url"] else "")
  interests = ", ".join(f"[[interests#{i}]]" for i in d["linked_interests"]) or "_none matched_"
  principles = "\n".join(f"{n}. **{p['name']}**: {p['explanation']}" for n, p in enumerate(d["principles"], 1))
  moves = "\n".join(f"{n}. {m}" for n, m in enumerate(d["mental_moves"], 1))
  w = d["when_to_apply"]
  body = f"""# Framework: {d['framework_name']}

**Source:** {source_line}
**Linked Interests:** {interests}
**Tags:** #framework

---

## Core Idea
{d['core_idea']}

## Principles
{principles}

## Mental Moves / Procedures
{moves}

## When to Apply
- **Content:** {w['content']}
- **Code:** {w['code']}
- **Projects / Decisions:** {w['project']}

## Anti-Patterns
{bullets(d['anti_patterns'])}

## Source Genealogy
{bullets(d['genealogy'])}

## Provenance
{d['provenance_note']}

## Applications Log
-
"""
  fm = frontmatter(cfg, agent, run_id, "framework", {
    "source": f'"{source_line}"', "applies-to": "[content, code, project]",
  })
  return write(cfg.frameworks / f"{slugify(d['slug'] or d['framework_name'])}.md", fm + body)


def source_note(cfg: Config, d: dict, framework_path: Path, agent: str, run_id: str) -> Path:
  src = d["source"]
  slug = slugify(src["title"]) or slugify(d["framework_name"])
  fm = frontmatter(cfg, agent, run_id, "source", {
    "id": f"src-{today().replace('-', '')}-{slug[:24]}",
    "title": f'"{src["title"]}"',
    "source_author": f'"{src["author"]}"',
    "kind": src["kind"],
    "topics": "[" + ", ".join(d["linked_interests"]) + "]",
    "extracted_frameworks": f'["[[{framework_path.stem}]]"]',
    "last_processed": today(),
  })
  body = f"# Source: {src['title']}\n\n{src['url'] or ''}\n\nExtracted → [[{framework_path.stem}]]\n"
  return write(cfg.frameworks / "sources" / f"{slug}.md", fm + body)


def _package_body(cfg: Config, p: dict) -> str:
  hooks = "\n\n".join(f"### Angle {chr(65 + i)}: {h['style'].title()}\n> {h['text']}" for i, h in enumerate(p["hooks"]))
  points = "\n".join(f"{n}. {t}" for n, t in enumerate(p["talking_points"], 1))
  sources = ", ".join(wikilink(cfg, s) for s in p["source_notes"]) or "-"
  return f"""# Curation: {p['title']}

**Interest:** [[interests#{p['interest']}]]
**Sources:** {sources}

---

## The Core Thesis
{p['thesis']}

**Why it's non-obvious:** {p['why_non_obvious']}

## Hook Angles

{hooks}

## Key Talking Points
{points}
"""


def next_curation_number(cfg: Config) -> int:
  folder = cfg.engine / "03-pipeline" / "01-curation"
  nums = [int(p.name.split("-")[1]) for p in folder.glob("curation-*.md") if p.name.split("-")[1].isdigit()]
  return max(nums, default=0) + 1


def curation_package(cfg: Config, p: dict, agent: str, run_id: str) -> Path:
  n = next_curation_number(cfg)
  fm = frontmatter(cfg, agent, run_id, "curation")
  path = cfg.engine / "03-pipeline" / "01-curation" / f"curation-{n:03d}-{slugify(p['slug'] or p['title'])}.md"
  return write(path, fm + _package_body(cfg, p))


def rejected_section(rejected: list[dict], key: str = "idea") -> str:
  if not rejected:
    return ""
  rows = "\n".join(f"| {r.get(key) or r.get('title')} | {r.get('url', '')} | {r['reason']} |" for r in rejected)
  return f"\n## Rejected (taste stays visible)\n| Idea / source | URL | Why rejected |\n|---|---|---|\n{rows}\n"


def signal(cfg: Config, s: dict, agent: str, run_id: str) -> Path:
  folder = {"paper": "papers", "repo": "repos", "postmortem": "postmortems", "web": "web"}[s["kind"]]
  fm = frontmatter(cfg, agent, run_id, "signal", {"kind": s["kind"]})
  body = f"""# Signal: {s['title']}

**Source URL:** {s['url']}
**Interest:** [[interests#{s['interest']}]] · **Signal-to-noise:** {s['signal_to_noise']}

## Core Mechanism
{bullets(s['mechanism'])}

## Genealogy
{s['genealogy']}

## Tweet Angle
> {s['tweet_angle']}
"""
  return write(cfg.engine / "02-signals" / folder / f"{slugify(s['title'])[:80]}.md", fm + body)


def thread(cfg: Config, d: dict, source: Path, out_dir: Path, agent: str, run_id: str) -> Path:
  tweets = "\n\n---\n\n".join(f"### Tweet {n} ({t['label']})\n{t['text']}" for n, t in enumerate(d["tweets"], 1))
  fm = frontmatter(cfg, agent, run_id, "twitter-thread", {
    "source_note": f'"[[{source.stem}]]"', "tweet_count": len(d["tweets"]),
  })
  body = f"""# Thread Draft: {d['title']}

**Why this hook:** {d['hook_rationale']}
**Credits:** {', '.join(d['credits']) or '-'}

---

{tweets}
"""
  return write(out_dir / f"{slugify(d['slug'] or d['title'])}.md", fm + body)


def journey(cfg: Config, d: dict, agent: str, run_id: str) -> Path:
  tweets = "\n\n---\n\n".join(f"### Tweet {n}\n{t}" for n, t in enumerate(d["tweets"], 1))
  fm = frontmatter(cfg, agent, run_id, "journey")
  body = f"""# Journey {today()}: {d['title']}

## What I built
{bullets(d['built'])}

## What broke / surprised me
{bullets(d['broke'])}

## The decision (and why)
{d['decision']}

## Proof
{bullets(d['proof'])}

## Tweet candidates

{tweets}
"""
  return write(cfg.twitter / "journey" / f"{today()}-{slugify(d['slug'] or d['title'])}.md", fm + body)


def build_brief(cfg: Config, d: dict, framework_slug: str, agent: str, run_id: str) -> Path:
  refs = "\n".join(f"| {n} | {r['name']} | {r['url']} | {r['stealing']} |" for n, r in enumerate(d["references"], 1))
  elements = "\n\n".join(
    f"""### {e['id']}: {e['name']}
- **Seen at:** {e['seen_at']}
- **What it is:** {e['what']}
- **Likely implementation:** {e['implementation']}
- **Why it works:** {e['why_it_works']}
- **Steal (mechanism):** {e['steal']}
- **Transform (our expression):** {e['transform']}""" for e in d["elements"])
  fm = frontmatter(cfg, agent, run_id, "build-brief", {"framework": f'"[[{framework_slug}]]"'})
  body = f"""# Build Brief: {d['title']}

## Goal
{d['goal']}

## References (steal from many, credit all)
| # | Source | URL | What we're stealing |
|---|--------|-----|---------------------|
{refs}

## Element Breakdown
{elements}

## Stack Suggestion
{d['stack']}

## Do NOT Copy
{bullets(d['do_not_copy'])}

## Acceptance Criteria
{chr(10).join(f'- [ ] {a}' for a in d['acceptance'])}

## Credits
{bullets(d['credits'])}
"""
  slug = re.sub(r"-?build-brief$", "", slugify(d["slug"] or d["title"]))
  return write(cfg.frameworks / "briefs" / f"{today()}-{slug}-build-brief.md", fm + body)


def build_report_section(d: dict, agent: str, repo: Path, branch: str) -> str:
  skipped = "\n".join(f"- {s['id']}: {s['reason']}" for s in d["elements_skipped"]) or "-"
  return f"""

---

## Build Report ({today()} · {agent})
**Repo:** `{repo}` · **Branch:** `{branch}` · **Not committed.** Review the diff, then commit yourself.

{d['summary']}

**Elements done:** {', '.join(d['elements_done']) or '-'}
**Skipped:**
{skipped}

**Files changed:**
{bullets(d['files_changed'])}

**Preview:** {d['how_to_preview']}
"""


def append_application(framework_file: Path, mode: str, output: Path) -> None:
  """Close the loop: record on the framework where it was applied."""
  if not framework_file.exists():
    return
  text = framework_file.read_text(encoding="utf-8").rstrip() + "\n"
  line = f"- {today()} · {mode} · [[{output.stem}]]"
  marker = "## Applications Log"
  if f"{marker}\n-\n" in text:  # empty placeholder bullet
    text = text.replace(f"{marker}\n-\n", f"{marker}\n{line}\n", 1)
  elif marker in text:  # it's the last section by convention
    text += f"{line}\n"
  else:
    text += f"\n{marker}\n{line}\n"
  framework_file.write_text(text, encoding="utf-8")

def competitor_research(cfg: Config, d: dict, agent: str, run_id: str) -> Path:
  slug = slugify(d.get("slug") or d.get("target", "competitor-research"))
  idea_dir = cfg.vault / "ideas" / slug
  if idea_dir.is_dir():
    target_path = idea_dir / "research.md"
  else:
    target_path = cfg.engine / "03-pipeline" / "01-curation" / f"compete-{slug}.md"

  fm = frontmatter(cfg, agent, run_id, "competitor-research", {
    "target": f'"{d.get("target", "")}"',
    "verdict": d.get("recommendation", {}).get("verdict", "unknown"),
  })

  hypo_rows = "\n".join(
    f"| {h['id']} | {h['hypothesis']} | {h['risk_level'].title()} | {h['expected_signal']} | {h['verdict'].title()} |"
    for h in d.get("hypotheses", [])
  ) or "| - | - | - | - | - |"

  comp_rows = "\n".join(
    f"| {c['name']} | [{c['url']}]({c['url']}) | {c['category']} | {c['value_prop']} | {c['pricing_model']} | {', '.join(c['strengths'])} | {', '.join(c['weaknesses'])} |"
    for c in d.get("competitors", [])
  ) or "| - | - | - | - | - | - | - |"

  grave_items = "\n".join(
    f"- **{g['name']}**: {g['root_cause_of_death']}" for g in d.get("graveyard", [])
  ) or "- _None identified_"

  diff = d.get("differentiation", {})
  patterns = d.get("proven_patterns", {})
  rec = d.get("recommendation", {})

  body = f"""# 🔍 Exploration & Competitor Intelligence: {d.get('target', slug)}

> **Slug:** `{slug}` · **Verdict:** `{rec.get('verdict', 'N/A')}`

---

## 🎯 1. Target Hypotheses & Intent
| # | Hypothesis Under Test | Risk Level | Expected Signal | Verdict |
|---|---|---|---|---|
{hypo_rows}

---

## 🏢 2. Direct Competitors & Market Incumbents
| Competitor | URL | Category | Value Prop | Pricing | Strengths | Weaknesses |
|---|---|---|---|---|---|---|
{comp_rows}

---

## 🔴 3. The Graveyard (Failed Predecessors)
{grave_items}

---

## 🟢 4. What Works (Proven Value & Demand)
- **Must-Have Triggers:**
{bullets(patterns.get('must_have_triggers', []))}
- **Willingness to Pay:** {patterns.get('willingness_to_pay', 'N/A')}
- **Sticky Workflows:**
{bullets(patterns.get('sticky_workflows', []))}

---

## ⚡ 5. Differentiation & Entry Wedge
- **Counter-Positioning:** {diff.get('counter_position', 'N/A')}
- **Entry Wedge:** {diff.get('entry_wedge', 'N/A')}
- **Novel Mechanism:** {diff.get('novel_mechanism', 'N/A')}

---

## ⚖️ 6. Strategic Verdict & Next Actions
**Strategic Synthesis:**
> {rec.get('strategic_synthesis', 'N/A')}

**Next Actions:**
{bullets(rec.get('next_actions', []))}
"""
  return write(target_path, fm + body)


def set_status(path: Path, status: str, note: str = "") -> None:
  if status not in STATUS_FLOW:
    raise ValueError(f"status must be one of {STATUS_FLOW}")
  text = path.read_text(encoding="utf-8")
  if not text.startswith("---"):
    raise ValueError(f"{path.name} has no frontmatter")
  end = text.index("\n---", 3)
  fm, body = text[:end], text[end:]
  lines = [l for l in fm.splitlines() if not l.startswith(("status:", "review_note:", "reviewed:"))]
  lines += [f"status: {status}", f"reviewed: {today()}"]
  if note:
    lines.append(f'review_note: "{note}"')
  path.write_text("\n".join(lines) + body, encoding="utf-8")
